---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
documentclass: book
---

```{block type='savequote', include=knitr::is_latex_output(), quote_author='(ref:chapter2-quote)'}
A straight line may be the shortest distance between two points, but it is by no means the most interesting
```
(ref:chapter2-quote) --- Third Doctor

# Chapter 3: Primary analysis of lipid regulating agents and dementia
\minitoc <!-- this will include a mini table of contents-->

## Additional ideas

One of the problems I'll point out with the trials in the systematic review chapter (Chapter \@ref(chapter-2-heading)) is that they only included people with a high cardiovascular risk - we are kind of doing the same by using elevated test cholesterol results as the index event.

## Aims



## Methods

### Estimation methods

Potential biases included time varying confounding, selection bias due to censoring on death and 
We performed a Cox 

### Estimating the value of the time-varying confounders

Mean time from index event to first prescription of statins was 2.4 years. This negates the promised benefit of ruling out confounding by indication (where the test result leads to the prescription of the treatment and also increases the risk of the outcome, distorting the relationship between the two), as there is no relationship between index TC/LDL-c and eventual LRA prescription.

Additionally, the time between index event and prescription does lead to a problem in terms of time varying confounding, as an average time of 2.4 years between current measurement of the covariates and treatment switching means there is plenty of time for the value of the covariate to change. This is problematic when the descision to change treatments (in this case to move from no LRA use to LRA use) is influenced by a set of prognostic factors that in turn may have been influenced by the inital treatment decision, as is likely to be the case for a range of covariates included in the model. For example:

_No CVD (t=0) -> No LRA (t=0) -> CVD (t=1) -> LRA (t=1) -> Dementia (t=2)_

In this case, the decision to move to LRA use is influenced by CVD status at _Time 1_, which will not be captured by adjusting only for CVD status at _Time 0_.

In practice, this means that the value of the prognostic factor should be regularly captured

However, in electronic health records, a change in the value of the prongostic factors is only important if it is recorded in a patients record, as for it to have an impact on treatment decisions, it must be recorded.

This means we can find the most recent value of the covariate before the switch and apply a marginal structural model approach, filling all values for that variable before the most recent measure with the baseline measurement, and all after the most recent meausure with the value of the most recent measure (on the basis that you won't go from having CVD back to not having CVD).

i.e.
Timepoint 12345678
CVD       00001111
Treatment 00000111 

Split into 3 month blocks since index event and use the same approach as above to work out the values of each covariate at each time point.

Note: this will be harder for things that are not dichotmous and can go up as well as down. Examples include total cholesterol and BMI, which can go up as well as down. 


### The effect of total cholesterol or LDL-cholesterol on LRA prescription

It would be fair to assume that the baseline total cholesterol/LDL-cholesterol would at least in part predict the liklihood of someone being prescribed a statin. 


