---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
  bookdown::word_document2: default
  bookdown::html_document2: default
documentclass: book
---

```{block type='savequote', include=knitr::is_latex_output(), quote_author='(ref:intro-quote)', echo = FALSE}
Hold
```
(ref:intro-quote) --- Hold

# Individual participant data meta-analysis {#ipd-heading}
\minitoc <!-- this will include a mini table of contents-->

## Lay Summary

<!----------------------------------------------------------------------------->
&nbsp;



<!----------------------------------------------------------------------------->
&nbsp;

## Introduction

Is there a good way to visualise input of cohorts into an IPD analysis?

Justify analysis based on findings of systematic review - suggestion of variation of effect by age, specifically 



<!----------------------------------------------------------------------------->
&nbsp;

## Methods

As part

As part of the IPD analysis, relevant cohort studies were identified from the sty and approached. In the first instance, the corresponding author on the main man

Talk about how different covariates were managed across cohorts, 
c
<!-- TODO Read this[@riley2020] -->


<!----------------------------------------------------------------------------->
&nbsp;

### Data sources

Several cohort studies were approach  

<!-- Need exact number approach -->

As part of this Chapter, I will use individual patient data from a range of sources. These sources are described here in detail for reference.

These data source



Each should have: 

* Description (including observation period, numbers, numbers with outcome, etc)
*

<!----------------------------------------------------------------------------->
&nbsp;

#### Epic Norfolk

The European Prospective Investigation of Cancer - Norfolk is a  [@riboli1997; @riboli2002]


Has only 8 events

```{r tests, }

```

#### CaPS

#### CPRD

The Clinical Practice Research Datalink (CPRD) is a large population-based, electronic health record (EHR) database.[@herrett2015] containing the primary care records for more than 10 million primary care patients in England, and is broadly representative of the UK population in terms of age, sex and ethnicity.[@herrett2015; @mathur2014]

The CPRD is introduced more fully in . Briefly, a similar approach to the cohort definition as used in Chapter

Participants were included from the first date of lipid measurement, so no issues with immortal time bias as discussed in Chapter ...

Additionally, ther number of participants is larger in this analysis as there is no restriction on the level which lipids should be in order to be included in the analysis.

the


#### EPIC Norfolk

#### Generation Scotland



#### NICOLA



#### TRACK HD



#### Whitehall II

_The Whitehall II study is a prospective cohort study of 10 308 participants (70% men), aged 35–55 years and recruited between 1985 and 1989 from 20 London-based Civil service departments (https://www.ucl.ac.uk/whitehallII). Clinical examinations have been performed in 1991-1994, 1997-1999, 2002-2004, 2007-2009, 2012-2013, 2015-2016 with the data from circulating metabolomic traits and cognitive testing for the present study obtained from the 1997-1999 clinic phase._ - taken from EN ID: 2140



included in previous IPD meta-analysis (Endnote ID: 2140)

Different approaches to combining subgroups. [@fisher2017]

<!-- Be clear on the different types of databases, e.g. those where users are followed up regularly vs those where participants are captured via EHR -->

<!----------------------------------------------------------------------------->
&nbsp;

### Cohorts provided data but ultimately excluded

Several cohorts were excluded on the basis of a lack of exposure variables, including Cam-CAN (had cardiovascular category, but only contained blood pressure).

#### BRACE

Likley had dementia at baseline

#### Memento
Excluded as criteria for entry was outpatients from memory clinic (unlikely to be dementia free at baseline)

#### Generation Scotland

Cross-sectional data only

#### NICOLA

NICOLA study - only had cross-sectional data

#### ELSA

Data provided but only had ever high cholesterol as a binary variable. Not compatible with 

<!----------------------------------------------------------------------------->
&nbsp;


### Cohorts identified the systematic review but excluded from the IPD analysis

<!-- Should also include a list of reasons why specific additional cohorts were not included - some like the EHR might be too big to get -->

Electronic health record co

LBC - 1936

Taiwan etc,

<!----------------------------------------------------------------------------->
&nbsp;

### Cohorts approach but received no answer

Maybe discuss here t

This was particularly frustrating in the case of cohorts which had a dedicated data access panel, for example, the Three City Study. Despite multiple attempts to contact the team, there was no response received.



<!-- TODO Will need some method to define how/from where the different cohorts were obtained. -->


<!----------------------------------------------------------------------------->
&nbsp;

### Data cleaning

Across all cohorts, data cleaning was performed in a similary manner, using commonly named variables, so that a single model could be applied using functional programming. 

The one exception to this is the CPRD data, which was held in a different system to the rest.

The advantage of this approach is that it reduces the liklihood of errors in model mis-speciication if needing to change variables names from cohort to cohort.



For all cohorts, the first lipid measurement was used for the exposure method, 

For heterogeneity across the cohorts, the total time-at-risk was investigated.

<!-- TODO Create similar crude rate table as for CPRD analysis chapter -->


<!----------------------------------------------------------------------------->
&nbsp;

### Missing data

Talk about missing data was handled <!-- IDEA See Sean's thesis for some additional detail on this -->  

<!----------------------------------------------------------------------------->
&nbsp;

### Risk of bias assessment

Risk of bias assessment was performed for each of the included cohorts using the relevant tool described in Section \@ref(risk-of-bias).

There is some concerns about performing risk of bias assessments on your own analysis, and so 

<!--- Inlcude CPRD analysis here, but dou --->

<!----------------------------------------------------------------------------->
&nbsp;

### Analysis

<!-- TODO talk about different methods - see here: https://onlinelibrary.wiley.com/doi/10.1002/sim.8516 -->

All analysis were standardised by changes in 1-SD of the exposure variable. 

This was done to aid interpretability of the outcome. 

Similary, 

Clustering within studies was accounted for, given the evidence that ...[@abo-zaid2013]

Stratified by age-at-entry and sex, and ethnicity where possible.


Hazard ratios were utilised to 


In order to investigate the interaction of sex with 

A two-stage model was used out of necessity, with the one-stage model being recluded by the different datasets being in protected data silos. 

A discrete proportional hazards model was employed to account for the interval censoring introduced by design o fthe longitudinal cohort studies.[@wang2017]

<!-- TODO Figure showing the outline of interval censored studies. -->

<!----------------------------------------------------------------------------->
&nbsp;

## Results

Data


<!----------------------------------------------------------------------------->
&nbsp;

## Discussion

Useful citation for discussion[@levis2021]

### Limitations

#### Low response rate to request for data

<!-- TODO Plot showing when datasets requested were published and comparing this with the -->


<!-- TODO text -->




This review had a low response rate to requests for data access.

While this is not unexpected, given that a review of IPD studies published between 1987 and 2015 found that fewer than half managed to obtained data from greater than 80% of studies, and that in many cases, the exact percentage of studies for which data was obtained was not accurately reported.
test
There are likely several reasons for this. 

* Individual participant data meta-analysis including studies other than randomised controlled trials have less success in obtaining individual participant data from studies.[@nevitt2017a] 

* While there is no

For many other reasons also - if 

A potential further reason was highlighted during my attendance at the 

Letters sent to all cohorts identified through the systematic review <!-- TODO will need quite a bit here on the numbers approached and how they responded if at all. Will also need to comment on the additional tactics used.  -->



This is likely due to my junior position as a early career research combined with the impact 

Range of reasons why data is not readily available. Privacy concerns, concerns around scoping or "parasitic" behaviour, and a lack of trust (i.e. primary researchers do not trust secondary researchers).<!-- TODO CITATION NEEDED: paper on trust as a big issue + paper on systematic review of barriers to data sharing -->
 
Unfortunately, 


The low response rate and the


Whether or not to press ahead with an IPD analysis in the absence of all (or even most) data is a personal decision, and some have highlighted where they decided not to pursue an IPD study.[@jaspers2014] 




<!-- However, fewer than half of systematic reviews with IPDMA, published between 1987 and 2015, retrieved data from at least 80% of relevant studies and from at least 80% of relevant participants [16]. The number of IPDMAs increased over this period [17], but data retrieval rates remained unchanged [16, 18]. Inability to include eligible studies compromises the systematic review’s purpose, decreases study power, and leads to healthcare decisions based on an incomplete, potentially biased data sample (studies with available data may differ from those whose data are not available) [10, 19, 20]. However, analysis combining individual and study level data may mitigate these effects [3, 21]. from [@ventresca2020a] -->


&nbsp;
<!----------------------------------------------------------------------------->

### Reflections on data access

Describe your experience of trying to access the DPUK - while a great resources, frustrating at times. The portal would benefit from a centralised management system and 

Even with the guaranteed data access afforded by the DPUK, accessing sufficient data was

<!----------------------------------------------------------------------------->
&nbsp;

### Study within a review

In future, it could have been worth running a "study within a review", such as that used to examine the best method [@godolphin2019a] to identify and access study data.

Previous SWARs have 

\newpage

## References