---
bibliography: bibliography/references.bib
csl: bibliography/nature.csl
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
  bookdown::word_document2: 
      toc: false
      toc_depth: 3
      reference_docx: templates/word-styles-reference-01.docx
      number_sections: false 
  bookdown::html_document2: default
documentclass: book
---

```{block type='savequote', include=knitr::is_latex_output(), quote_author='(ref:intro-quote)', echo = FALSE}
Hold
```
(ref:intro-quote) --- Hold

<!-- TODO Add this to the Chapter summary in the introduction and  -->

<!----------------------------------------------------------------------------->
&nbsp;

<!-- ### Triangulation  -->

<!-- TODO Have a look at this - potentially move to triangulation chapter -->

<!-- One key question for which multiple distinct sources of evidence were available were those looking at Laz -->

<!-- Consideration of the potential impact of the magnitude and direct of residual confounders/bias is not a major stretch from what is already happening in the assessment of the quality of evidence (GRADE) framework. Within GRADE, the overall quality of evidence can be upgraded when there is deemed to be unmeasured or residual confounding variables which reduce the. For example, if the propensity to treatment is related to comorbidity burden, but those on treatment still have better outcomes then those on control, it is likely that the true effect of the intervention is being underestimated. [@guyatt2011] -->

<!-- Without our framework and as part of the risk-of-bias assessments reported in \@ref(risk-of-bias-subheading), I attempted to records the direction of the bias, so that it could feed into the triangulation. -->


# Aetiological triangulation across evidence sources {#tri-heading}

## Lay Summary

<!----------------------------------------------------------------------------->
&nbsp;

## Introduction

This chapter will attempt to triangulate the evidence identified by the systematic review in Chapter \ref(sys-rev-heading)

### Data sources

This chapter builds on the comprehensive systematic review presented in CHapter \@re(sys-rev-heading), and incorporates the results of the analyses presented in Chapters \@ref(cprd-heading) & \@ref(ipd-heading).

<!----------------------------------------------------------------------------->

### Background to the causal question

Following best practice guidance, three 

Table with columns describing exposure, outcome, timepoint, other aspects (cumulative), and

This was also guideded by the forthcoming ROBINS-E tool, which has

<!----------------------------------------------------------------------------->

### Definition of the causal question

<!-- TODO See ROBINS-E for this, as to how to think about exposures -->

### Summary of triangulation

Need to check how much I talk about this in the introduction

Describe in detail

### Risk of bias tool

In addition, the tool also aim to capture the potential direction of bias for each result. Possible responses included: "Favours experimental", "Favours comparator", "Towards null", "Away from null", and "Unpredictable". Highlight that this is slightly different for the confounding domain in non-randomised studies.

These levels only apply to existing tools, not the MR tool. However, a similar approach was employed.

While the triangulation framework provides for inclusion of multiple distinct types of evidence, based on the scoping search, it is likely that the three main sources will be RCTs of statins, multivariable regression of prospective cohorts, and the use of genetic instruments in observational data (Mendelian Randomisation studies). One important difference between these approaches that will need to be addressed in the triangulation
is that RCTs relate to short-term modification of lipid levels, whereas Mendelian randomisation studies typically refer to lifelong exposures; and traditional observational epidemiology approaches may refer to short or longterm exposure (although are often not explicit about this). The triangulation will take these into account, for example by superimposing the studies on a hypothetical model for exposure-outcome relationship across the life course.


<!----------------------------------------------------------------------------->
&nbsp;

### Graphical representation

For the graphs, the direction of bias is important.

Where the direction of bias was unclear/could not be determined from the report, this is indicated

In order to aid with the triangulation exercise, a new method of presentation of these results was developed to enable detailed comparison across different studies contributing to the causal question.
The level of bias in each study is reported using coloured blocks, while the predicted direction of bias in that domain, categorised as towards or away from the null, is indicated using an arrow

Of note, a different approach was required for the confounding domains in the assesment tools used for non-randomised studies. Confounding in a study will either pull to the left or right, regardless of where the effect estimate is, while other domains will pull towards/away from the null (e.g. non-differential misclassification). In this case, the program accounted for the position of the effect estimate when assigning a directional arrow in relation to the positon of the effect estimate. 
For example, see Figure \@ref(), which shows an example study under the same confounding structure (protective), but with protective and harmful effect estimates. In this case, when the estimated effect is protective (Study 1), the arrow for the confounding domain indicates that the bias is pulling it away from the null. If the estimated effect is harmful, the arrow indicates that the results is being biased towards the null.

These graphs were built using the risk of bias tool described in Appendix \ref()

<!-- TODO Does immortal time bias not also have a consistent effect -->

<!----------------------------------------------------------------------------->

### Standardisation across study designs

Standardising across different measures of ex

Want best information across lipids, and so standardised across differnt measures

Fixing directions of effect - get everything pointing the same way

<!----------------------------------------------------------------------------->
### Analyses

Bias-adjusted meta-analysis [@higgins2008a]

<!----------------------------------------------------------------------------->

## Results

Summary of risk-of-bias/triangulation results

Percentage of domains for which a direction of bias could be assigned?

Compare bias-adjusted and

See what happens if using additive (l=1,m=2,s=3,c=4) vs multiplicative/log scale (l=1,m=2,s=4,c=8). Present adjusted results and meta-analysis of adjusted results.

Applicability/indirectness as an issue 
Compare with GRADE and cite George's example of 40% of effect predicted by MR seen when using statins for 5 years

<!----------------------------------------------------------------------------->

## Discussion

I hope this presents step forward in how researchers think about and visualise triangulation at the result level, rather than simply saying that certain 

### Challenges of real-life data

Compare and contrast with the nice example presented in the triangulation paper - realities of non-exemplars is that it is very hard to get this right. ALso highlight the issue with assigning a direct of bias in many studies

### Need for new methods 

Can I suggest any empirical studies that need to be performed? Average strength of immortal time bias/etc?







