---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
documentclass: book
---

# Individual participant data meta-analysis {#ipd-heading}
\minitoc <!-- this will include a mini table of contents-->


## Methods

### Data sources

Several cohort studies were approach  

<!-- Need exact number approach -->

As part of this Chapter, I will use individual patient data from a range of sources. These sources are described here in detail for reference.

Should also include a list of reasons why specific additional cohorts were not included - some like the EHR might be too big to get

Each should have: 

* Description (including observation period, numbers, numbers with outcome, etc)
* Whether they are a known genetically at-risk cohort
*

### Epic Norfolk

The European Prospective Investigation of Cancer - Norfolk is a  [@riboli1997; @riboli2002]


```{r tests, }

```


Different approaches to combining subgroups. [@fisher2017]

## Risk of bias assessment

Risk of bias assessment was performed for each of the included cohorts using the relevant tool described in Section \@ref(risk-of-bias).

<!--- Inlcude CPRD analysis here, but dou --->


## Data cleaning

## Discussion

Letters sent to all cohorts identified through the systematic review - will need quite a bit here on the numbers approached and how they responsed if at all. Will also need to comment on the additional tactics used. 


This is likely due to my junior position as a early a

Range of reasons why data is not readily available.

Unfortunately, 

As part of this, an analysis of 


## Discussion

Describe your experience of trying to access the DPUK - while a great resources, furstrating at times.
