---
bibliography: bibliography/references.bib
csl: bibliography/nature.csl
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
  bookdown::word_document2: 
      toc: false
      toc_depth: 3
      reference_docx: templates/word-styles-reference-01.docx
      number_sections: false 
  bookdown::html_document2: default
documentclass: book
---

```{block type='savequote', include=knitr::is_latex_output(), quote_author='(ref:intro-quote)', echo = FALSE}
Hold
```
(ref:intro-quote) --- Hold

<!-- TODO Add this to the Chapter summary in the introduction and  -->

<!----------------------------------------------------------------------------->
&nbsp;

<!-- ### Triangulation  -->

<!-- TODO Have a look at this - potentially move to triangulation chapter -->

<!-- One key question for which multiple distinct sources of evidence were available were those looking at Laz -->

<!-- Consideration of the potential impact of the magnitude and direct of residual confounders/bias is not a major stretch from what is already happening in the assessment of the quality of evidence (GRADE) framework. Within GRADE, the overall quality of evidence can be upgraded when there is deemed to be unmeasured or residual confounding variables which reduce the. For example, if the propensity to treatment is related to comorbidity burden, but those on treatment still have better outcomes then those on control, it is likely that the true effect of the intervention is being underestimated. [@guyatt2011] -->

<!-- Without our framework and as part of the risk-of-bias assessments reported in \@ref(risk-of-bias-subheading), I attempted to records the direction of the bias, so that it could feed into the triangulation. -->


# Aetiological triangulation across evidence sources {#tri-heading}

\minitoc <!-- this will include a mini table of contents-->

## Lay Summary

<!----------------------------------------------------------------------------->
&nbsp;

## Introduction

This chapter will attempt to triangulate the evidence identified by the systematic review in Chapter \ref(sys-rev-heading)

### Data sources

This chapter builds on the comprehensive systematic review presented in CHapter \@re(sys-rev-heading), and incorporates the results of the analyses presented in Chapters \@ref(cprd-heading) & \@ref(ipd-heading).

<!----------------------------------------------------------------------------->

### Qualitative triangulation

<!-- TODO Need to talk about fibrates here too -->

__Statins and all-cause dementia__

This conflicts with the findings of our analysis, where statin use was associated with an increased risk of all-cause dementia (`r anydem_text`). Some of the included studies in the meta-analysis specifically exclude vascular dementia from the definition of all-cause dementia,[@chao2015] which may limit the ability for comparison with our findings for the all-cause dementia outcome.

Additionally, a previous analysis of the THIN EHR database using a propensity-score matched analysis found a protective effect of statins on all-cause dementia (HR:0.81, 95%CI:0.69-0.96)[@smeeth2009]. 

&nbsp;

__Statins and Alzheimer's disease__

Our results are broadly in line with the findings of two distinct approaches examining the effect of statin treatment on subsequent Alzheimer's disease. No randomized trials of statins for the prevention of Alzheimer's disease have been reported, but a recent meta-analysis of 20 observational studies found statins were associated with a reduced risk of Alzheimer's disease (RR 0.69, 95% CI 0.60–0.80) with stronger evidence than observed in our analysis.[@poly2020] This review included case-control studies and analyses likely to be at risk of immortal time bias, which may account for the discrepancy with our findings. Additionally, a recent Mendelian randomization study examining the effect of genetic inhibition of HMGCR on Alzheimer’s disease (a genetic proxy for statin treatment) provided equivocal evidence (OR: 0.91, 95%CI: 0.63-1.31) but was consistent with our results.[@williams2020]

Our additional analyses stratified by statin properties found little evidence of differences in associations of lipophilic and hydrophilic statins and incidence of Alzheimer’s disease, consistent with a recent meta-analysis of observational studies.[@chu2018]

&nbsp;

__Statins and vascular/other dementia__

Far fewer studies have tested the association between lipid-regulating agents and vascular dementia or other dementias. A recent review found four observational studies examining the association of statins and vascular dementia found limited evidence for an effect (RR:0.93, 95% CI 0.74–1.16).[@poly2020] This contrasts with the harmful association found in our analysis (`r vasdem_text`). When stratifying by lipid properties, lipophilic statins were more harmful than hydrophilic statins in vascular dementia, potentially due to their ability to cross the blood brain barrier.

&nbsp;

__Other drug classes__

Apart from statins, few studies examining a lipid-regulating agent have been reported (Chapter \@ref(sys-rev-methods-heading)/\@ref(sys-rev-results-heading)). 

One of the few classes for which a evidence was available were fibrates, which found little evidence of an association with all-cause dementia was identified,[@ancelin2012] inconsistent with our finding that patients prescribed fibrates had higher all-cause dementia risk than those prescribed other lipid lowering agents.

A previous Mendelian randomization study found little evidence that genetic variants that proxy for ezetimibe affect risk of Alzheimer’s disease (OR: 1.17, 95%CI: 0.73-1.87),[@williams2020] consistent with our findings. Note that this study was published in 2020 and so was not included in the review.


### Background to the causal question

Following best practice guidance, three 

Table with columns describing exposure, outcome, time-point, other aspects (cumulative), and

This was also guideded by the forthcoming ROBINS-E tool, which has

<!----------------------------------------------------------------------------->

### Definition of the causal question

<!-- TODO See ROBINS-E for this, as to how to think about exposures -->

This chapter will consider two questions


Firstly, an ter

Secondly an 

&nbsp;<!----------------------------------------------------------------------->  

## Terminology

The terminology used in describing different mechanisms by which an observed result may  complicate interpretation. This section clearly defines how each are used in h


Here, internal bias is used in terms of 

In contrast, external bias (also called indirectness, or )


Additionally, potential biases can be additive or proportional. Pro



### Summary of triangulation

Need to check how much I talk about this in the introduction

Describe in detail


### Evidence sources

As outlined in the thesis overview presented in Section \@ref(hold), the triangulation draws on the research produced in the preceding chapters.


a)	Proposed method for this chapter
i)	Example: LDL-c at midlife on Alzheimer’s disease risk
ii)	Specific causal effect of interest using ROBINS-E framework:
•	Population of interest: General population
•	Exposure of interest: Low density lipoprotein cholesterol
•	Exposure window of interest: Midlife (45-60)
•	How exposure over time should be summarized: Cumulative exposure
iii)	Identify relevant studies from evidence base
•	LDL-c assessed at midlife
•	MR of LDL-c
•	Statin use at midlife
iv)	Assess risk of bias in each result, define expected directions of each bias and plot
 
v)	Assign additive value to each level of bias (High = 0.2, Some concerns =0.1, Low = 0), assign sign to these values based on predicted direction and sum across result
vi)	E.g. for effect estimate 0.71 (0.57-0.89):

Element	D1	D2	D3	D4	D5	D6	D7	Overall
Bias	High	Some concerns	Low	Low	Low	Some concerns	Some concerns	Serious
Direction	Left	Away from null	-	-	-	Towards null	Away from null	
Modifier	-0.2	-0.1	0	0	0	0.1	-0.1	-0.3

vii)	Assign a proportional value representing the indirectness for each result
•	Statin studies would give smaller proportion (e.g. 0.7) of effect observed for generally lower lipids, as they would reduce cumulative exposure 
•	SNPs predict quite strongly LDL-c and so would have minimal indirectness
viii)	Combine in a bias-adjusted meta-analysis 


###	Limitations

In previous attempts at bias/indirectness-adjusted meta-analysis, the extent to each was assessed via a elictation process using a number of experts.

Ideally, the modifying values )

i)	Ideally modifying values (both internal and external) would be based on empirical research, but in absence of this, sufficient to model multiple values (High = 0.1, Some concerns =0.05, Low = 0) and relationships (High = 0.3, Some concerns =0.1, Low = 0)? 
Need range around modifying values, as total variance of the biases is added to the total variance of the studies (elicitation on scale presented above asks for range rather than single estimate

### Risk of bias tool



In addition, the tool also aim to capture the potential direction of bias for each result. Possible responses included: "Favours experimental", "Favours comparator", "Towards null", "Away from null", and "Unpredictable". Highlight that this is slightly different for the confounding domain in non-randomised studies.

These levels only apply to existing tools, not the MR tool. However, a similar approach was employed.

While the triangulation framework provides for inclusion of multiple distinct types of evidence, based on the scoping search, it is likely that the three main sources will be RCTs of statins, multivariable regression of prospective cohorts, and the use of genetic instruments in observational data (Mendelian Randomisation studies). One important difference between these approaches that will need to be addressed in the triangulation
is that RCTs relate to short-term modification of lipid levels, whereas Mendelian randomisation studies typically refer to lifelong exposures; and traditional observational epidemiology approaches may refer to short or longterm exposure (although are often not explicit about this). The triangulation will take these into account, for example by superimposing the studies on a hypothetical model for exposure-outcome relationship across the life course.


<!----------------------------------------------------------------------------->
&nbsp;

### Graphical representation

For the graphs, the direction of bias is important.

Where the direction of bias was unclear/could not be determined from the report, this is indicated

In order to aid with the triangulation exercise, a new method of presentation of these results was developed to enable detailed comparison across different studies contributing to the causal question.
The level of bias in each study is reported using coloured blocks, while the predicted direction of bias in that domain, categorised as towards or away from the null, is indicated using an arrow

Of note, a different approach was required for the confounding domains in the assesment tools used for non-randomised studies. Confounding in a study will either pull to the left or right, regardless of where the effect estimate is, while other domains will pull towards/away from the null (e.g. non-differential misclassification). In this case, the program accounted for the position of the effect estimate when assigning a directional arrow in relation to the positon of the effect estimate. 
For example, see Figure \@ref(), which shows an example study under the same confounding structure (protective), but with protective and harmful effect estimates. In this case, when the estimated effect is protective (Study 1), the arrow for the confounding domain indicates that the bias is pulling it away from the null. If the estimated effect is harmful, the arrow indicates that the results is being biased towards the null.

These graphs were built using the risk of bias tool described in Appendix \ref()

<!-- TODO Does immortal time bias not also have a consistent effect -->

<!----------------------------------------------------------------------------->

### Standardisation across study designs

Standardising across different measures of ex

Want best information across lipids, and so standardised across differnt measures

Fixing directions of effect - get everything pointing the same way

<!----------------------------------------------------------------------------->
### Analyses

Bias-adjusted meta-analysis [@higgins2008a]


## Triangulation across exisiting evidence and evidence produced in this thesis

### Overview of triangulation {#triangulation-overview}

Using the review of the literature as a guide to identify useful further studies that could be performed, I then performed . 

Summary table of different studies and results

<!----------------------------------------------------------------------------->
&nbsp;

## Qualitative vs qunatitative triangulation

### Researcher positionality statement



<!----------------------------------------------------------------------------->
&nbsp;

## Discussion of E-values

How strong unmeasured confounding would have to be in order to explain the observed effect.

Heavily criticised in a range of papers.

<!----------------------------------------------------------------------------->
&nbsp;

## Use of concensus panel to bring everything together

<!----------------------------------------------------------------------------->

## Results

Summary of risk-of-bias/triangulation results

Percentage of domains for which a direction of bias could be assigned?

Compare bias-adjusted and

See what happens if using additive (l=1,m=2,s=3,c=4) vs multiplicative/log scale (l=1,m=2,s=4,c=8). Present adjusted results and meta-analysis of adjusted results.

Applicability/indirectness as an issue 
Compare with GRADE and cite George's example of 40% of effect predicted by MR seen when using statins for 5 years

<!----------------------------------------------------------------------------->

## Discussion

I hope this presents step forward in how researchers think about and visualise triangulation at the result level, rather than simply saying that certain 

### Challenges of real-life data

Compare and contrast with the nice example presented in the triangulation paper - realities of non-exemplars is that it is very hard to get this right. ALso highlight the issue with assigning a direct of bias in many studies

### Need for new methods 

Can I suggest any empirical studies that need to be performed? Average strength of immortal time bias/etc?







