---
output:
  bookdown::word_document2: 
      reference_docx: templates/word-styles-reference-01.docx   
  bookdown::pdf_document2:
    template: templates/brief_template.tex
  bookdown::html_document2: default
documentclass: book
---

```{block type='savequote', include=knitr::is_latex_output(), quote_author='(ref:intro-quote)', echo = FALSE}
Hold
```
(ref:intro-quote) --- Hold

# Discussion {#discussion-heading}
\minitoc <!-- this will include a mini table of contents-->

<!----------------------------------------------------------------------------->
## Triangulation across exisiting evidence and evidence produced in this thesis

### Overview of triangulation {#triangulation-overview}

Using the review of the literature as a guide to identify useful further studies that could be performed, I then performed . 

Summary table of different studies and results

<!----------------------------------------------------------------------------->
&nbsp;

## Qualitative vs qunatitative triangulation

### Researcher positionality statement



<!----------------------------------------------------------------------------->
&nbsp;

## Discussion of E-values

How strong unmeasured confounding would have to be in order to explain the observed effect.

Heavily criticised in a range of papers.

<!----------------------------------------------------------------------------->
&nbsp;

## Use of concensus panel to bring everything together

<!----------------------------------------------------------------------------->
&nbsp;

## Additional topics for the discussion

There are several addition topics I would like to cover:

* The difference between the peer review of the software vs. the peer review of papers. A conversation until everything is fixed/clear reporting guidelines/checklists, with acceptance dependent on them being implemented /built-in version control, and cross linking discussion points to changes through the linking of commits and comments.  Essentially, a more transparent and open

<!----------------------------------------------------------------------------->
&nbsp;

## Summary of findings (and implications for policy makers)

<!----------------------------------------------------------------------------->
&nbsp;

## Strengths and Limitations

There are several strengths and limitations to the work presented in this thesis. One particularly strength is the lengths gone to find all available published and unpublished evidence around the question, and to integrate this evidence in a coherent framework, taking into account the limitations of ach source and how these limitations may be used to provide 

Need for large simple trials for common disease where small treatment effect can have large effect - [@yusuf1984]

&nbsp;
<!----------------------------------------------------------------------------->

## Reproducible research

Reproducible and science has been a key theme running through this thesis, as reflected by the development of an open source tool to help search medRxiv and bioRxiv preprint metadata. In line with this, an open source copy of the code used to produce this thesis is available on GitHub, as is the code used to perform the analysis contained within it. 

Containerisation was used to ensure that the code is reproducible, in line iwht best practices

Commentary on the fact that the best you can do is replicate vs reproducible (due the closed nature of the data).

One is the ability to recreate the results given the same data and code, the other is the ability to recreate the results given the same code but a different dataset. IN theory it is possible to gain access the dataset given the information presented in Chapter \@(ref:cprd-analysis-heading). However, access is dependency on an ISAC application to the managing body of the CPRD. 

&nbsp;
<!----------------------------------------------------------------------------->

## Public involvement and engagement {#disc-PPI}

Involving and engaging the public and patients has been a central theme to this thesis. 

Public engagement activities included 

Public involvement also steered the creation of the topic

P

&nbsp;
<!----------------------------------------------------------------------------->

## Future work

Recommend future large scale GWAS of other dementia outcomes, notably vascular dementia, or the use of existing GWAS to  <!-- TODO At least one vascular dementia GWAS exists - find it and cite it here. -->

&nbsp;
<!----------------------------------------------------------------------------->

## Overall conclusions

