---
bibliography: bibliography/references.bib
csl: bibliography/nature.csl
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
  bookdown::word_document2: 
      reference_docx: templates/word-styles-reference-01.docx   
  bookdown::html_document2: default
documentclass: book
---

```{block type='savequote', include=knitr::is_latex_output(), quote_author='(ref:discussion-quote)', echo = TRUE}
Science knows it doesn't know everything.

Otherwise, it'd stop.
```

(ref:discussion-quote) --- Dara Ó Briain, 2008[@obriain2008] 

# Discussion {#discussion-heading}

&nbsp;

\minitoc <!-- this will include a mini table of contents-->

\newpage

::: {.laybox data-latex=""}
## Lay summary 

In this final chapter, I describe the results of each previous chapter and compare my results with those of two recent large studies. I describe how doctors and those working in public health should use the results of my work, and highlight issues that may limit the usefulness of my findings. Finally, I describe future research that would build on my findings to move the field forward.

:::

&nbsp;<!----------------------------------------------------------------------->  

## Introduction 

The central aim of this thesis was to infer the causal effect of blood lipid levels on dementia outcomes via evidence synthesis methods. In this discussion, I will review the contribution of each chapter to this aim, summarise the principal findings and methodological innovations of the thesis, and discuss the implications of my findings for both clinical and public health practice. I consider the overall strengths and limitations of this thesis as a coherent body of work and suggest avenues for impactful future research that would build on the research presented.

&nbsp;<!----------------------------------------------------------------------->  

### Chapter summary

This thesis is comprised of a mix of methodological and applied research chapters.

In __Chapter \@ref(background-heading)__, I introduced the core concepts considered in this thesis and framed the research presented in relation to a theoretical framework of evidence synthesis.

In __Chapter \@ref(sys-rev-tools-heading)__, I  presented a new tool for the systematic searching of health-related preprints and detailed two use cases for preprint metadata beyond the systematic searching of this evidence source.

In __Chapter \@ref(sys-rev-methods-heading)__, I described the methods of a comprehensive systematic review of all available evidence on the association of both lipid levels and lipid-regulating agents with dementia outcomes. The results of this analysis are then presented in __Chapter \@ref(sys-rev-results-heading)__.

In __Chapter \@ref(cprd-analysis-heading)__, I described an analysis of the association of lipid-regulating agent use and dementia outcomes in the CPRD, a large electronic health record database. I made use of positive and negative control outcomes to illustrate insufficiently controlled confounding.

In __Chapter \@ref(ipd-heading)__, I presented an individual participant data meta-analysis of the association of lipid levels and dementia outcomes, using previously unanalysed data accessed via the Dementia Platform UK.

Finally, in __Chapter \@ref(tri-heading)__, I proposed a new method for the systematic integration of multiple evidence sources as part of quantitative triangulation framework. I illustrated the method using two case studies (the effect of LDL-c on Alzheimer's disease and the effect of triglycerides on vascular dementia), drawing on the evidence identified or produced by previous chapters.

&nbsp;<!----------------------------------------------------------------------->  

## Summary of clinical findings

### Effect of blood lipids on dementia outcomes

Given that the results of the different components of this thesis are discussed in detail as part of the triangulation analysis (see Section \@ref(qual-tri)), here I briefly summarise the key findings.

Overall, I did not identify a consistent effect of any blood lipid fraction (total cholesterol, LDL cholesterol, HDL cholesterol or triglycerides) on any dementia outcome (all-cause dementia, Alzheimer's disease or vascular dementia). While published non-randomised studies provided evidence for a protective effect of lipid-lowering via statin use on Alzheimer's disease and the IPD analysis suggested a harmful effect of raised triglycerides on vascular dementia, these effects were not maintained when incorporated along with other sources of evidence in a quantitative triangulation framework. Similarly, the IPD analysis did not provide evidence for an interaction of patient characteristics (age/sex) with the association of blood lipids and dementia outcomes, other than a slight protective effect of male gender on the LDL-c/all-cause dementia relationship. However, this analysis was limited by the low number of cohorts analysed.

In the published literature, statins were by far the most studied lipid-regulating agent in relation to dementia outcomes. Given the large proportion of patients taking statins as indicated by my analysis of the CPRD data, this finding is unsurprising. Finally, there was a substantial absence of evidence for vascular dementia.

&nbsp;<!----------------------------------------------------------------------->  

### Comparison with new evidence

Since the searches underpinning the systematic review described in this thesis were performed (July 2019), further studies on this topic have been published. Two of these, notable for the analysis of large UK cohorts, are discussed here.

The first is a large-scale analysis of 953,635 patients in the CPRD, followed from their first LDL-c measurement.[@iwagami2021] The study found evidence for a slightly increased risk of dementia with higher LDL-c levels at mid-life, driven by the finding for the Alzheimer's disease subgroup. These results are consistent with the findings presented in this thesis, particularly as this study did not have access to _Apo_$\mathcal{E}4$ status and so could not adjust for confounding by this variable. _Apo_$\mathcal{E}4$ is a key risk factor for both Alzheimer's disease and raised LDL-c levels, <!-- TODO CITATION NEEDED --> and so could explain the harmful association observed. This is supported by a simulation analysis reported within this study, which used published information to predict that _Apo_$\mathcal{E}4$ would induce a risk ratio of 1.09 per 1-SD increase in LDL-c in the absence of a true causal effect.

The second analysis examined 502,226 participants in the UK Biobank, a large population-based prospective cohort study.[@gong2021; @sudlow2015] The analysis found no association between lipids measured at mid-life and dementia outcomes. This finding is again comparable to the results of this thesis. However, similar to the study discussed above, this analysis did not have access to genetic data and so may be subject to residual confounding by _Apo_$\mathcal{E}4$ genotype. 

&nbsp;<!----------------------------------------------------------------------->  

### Implications for clinical practice

Given the absence of any consistent signals across the evidence sources analysed, there are no clear indications for clinical practice arising from this thesis. While my research did not provide any strong evidence for an effect of lipid-lowering on dementia outcomes, the cumulative strength of evidence is also insufficient to rule out an effect.

Given this ambiguity, the use of statins should be restricted to their primary and well-understood purpose of lipid-lowering to reduce the risk of cardiovascular events. However, it is important to recognise that even under a scenario where a strong harmful effect of lipid-lowering on dementia outcomes was identified, whether or not to prescribe a statin at mid-life will always be guided by factors other than dementia prevention. Patients must live to a certain age in order to be at risk of dementia (with the exception of familial early-onset dementias), which is substantially less likely if hypercholesterolemia at mid-life is left unchecked.

In summary, clinicians should be aware of the uncertainty of evidence surrounding the effect of lipid-lowering on dementia outcomes and should be prepared to convey the same to patients.

&nbsp;<!----------------------------------------------------------------------->  

### Implications for public health

<!-- REVIEW Suggesting an ecological study? Is adding weak evidence really useful? Would it come with independent biases that would (in theory) bring a further dimension to the triangulation framework. -->

Similarly, given the ambiguity of evidence, there are no clear implications for public health practice. However, the role of public health, and particularly continuous population surveillance, may be important in providing a further source of evidence in relation to the effect of lipid lowering on dementia. As an illustrative example, the Cognitive Function and Ageing Study (CFAS) II (2008-2011) showed a reduction in the age-specific prevalence rates of dementia when compared to CFAS I (1989-1994).[@matthews2013] The authors interpreted this reduction as the result of improved education and better control of vascular risk factors, in line with broader thinking on the impact of population-level changes in risk factors.[@capewell2011] In a similar manner, public health practitioners could examine summary-level statistics of GP prescription data to attempt to relate lipid-lowering treatment to temporal or geographical trends in dementia incidence.

It may well prove difficult to assess if any observed trends are due to a true effect or to confounding or ecological biases. However, because dementia outcomes will be monitored anyway for incidence/prevalence estimation and planning of services/care, this approach could provide a ready source of further evidence with a distinct bias structure to the approaches already considered in this thesis.

&nbsp;<!----------------------------------------------------------------------->  

## Summary of methodological contributions

In addition to addressing the causal impact of lipids on dementia outcomes, the research described in this thesis represents a number of novel contributions to the field of evidence synthesis methodology.

&nbsp;<!----------------------------------------------------------------------->  

### Inclusion of preprinted evidence

Preprints are an important source of evidence, and future information specialists may wish to search health-related preprints as part of a wider systematic review. To support this, I developed a new tool, `medrxivr`, as discussed more fully in Chapter \@ref(sys-rev-tools-heading). The tool has been well received by the community, and its use in systematic reviews[@imai2021; @rojoa2021; @hamilton2021] and scoping searches[@grassly2020] has been reported. In addition, the preprint metadata provided by the tool has been used in several meta-research studies.[@kodvanj2020;@noone2020;@mcguinness2020DAScomparison]

&nbsp;<!----------------------------------------------------------------------->  

### Bias

One of the central methodological contributions of this thesis has been on the conduct, visualisation, and incorporation of bias assessments as part of an evidence synthesis exercise. 

In terms of assessment, I applied domain-based tools to evidence relevant to the effect of lipids on dementia outcomes and highlighted the limitation of the available tools for Mendelian randomisation studies. I also piloted and provided feedback on a forthcoming tool for assessing the risk of bias due to missing evidence. In the primary analysis of data from the CPRD, I used negative control outcomes to assess the potential for bias due to insufficiently controlled confounding by indication.

In terms of visualisation of bias, I have made a number of methodological contributions. I built a well-received R package to create paired forest plots (see Appendix \@ref(appendix-robvis)), and developed this further to enable users to produce the bias direction plots illustrated in Chapter \@ref(tri-heading). 

Finally, I made several novel contributions around the incorporation of bias into analyses. These were intended to encourage authors of reviews to actively consider the impact of bias in their syntheses, something that empirical evidence suggests happens infrequently at present.[@katikireddi2015] The new methods introduced by this thesis range from the forest plots stratified by overall risk of bias level presented in Chapter \@ref(sys-rev-results-heading) to the more advanced triangulation framework presented in Chapter \@ref(tri-heading).

&nbsp;<!----------------------------------------------------------------------->  

### Triangulation framework

The proposed quantitative triangulation framework represents the final novel contribution of this thesis to evidence synthesis methodology. Using pre-specified adjustment distributions mapped to the results of the domain-based risk-of-bias and indirectness assessments, this approach provides a systematic way to account for biases/indirectness across studies. In addition, it explicitly seeks to include both direct and indirect evidence and separates the assessment of bias/indirectness in each result from the definition of distributions representing the impact of bias/indirectness.

Ideally, this framework should be based on the results of a comprehensive systematic review, which identifies all evidence (both direct and indirect) related to a causal question of interest. This would represent a break from the current practice of limiting review to a single type of evidence, and  would result in fewer, more comprehensive reviews. In the current context of concern over research waste, a concentration of effort in fewer reviews may be advantageous. Section \@ref(rev-previous-reviews) illustrates the duplication of reviews in relation to the topic of this thesis, while an assessment of the COVID-19 literature found that, for a specific clinical question, there were substantially more reviews (25) than available primary studies (17).[@perez-gaxiola2021]

Finally, the framework proposed here could (fairly) be criticised over the validity of the prior distributions of bias/indirectness chosen. However, the assumptions made about the impact of bias in this thesis are no stronger than those made when synthesising effect estimates as though they were unbiased. The proposed framework at the very least recognises the uncertainty introduced by bias/indirectness and decreases the precision of the overall effect estimate on this basis. 

In summary, the proposed triangulation framework could enable better use of all available evidence to address causal questions.

&nbsp;<!----------------------------------------------------------------------->  

## Overall strengths and limitations

The strengths and limitations of each aspect of this thesis have been discussed in the respective chapter. Here, I highlight the strengths and weaknesses of this thesis as a body of work.

&nbsp;<!----------------------------------------------------------------------->  

### Strengths

There are four key strengths to this thesis as a whole. Firstly, the identification and triangulation of evidence across study designs and publication status sets this thesis apart from previous syntheses of the evidence on this topic. 

Additionally, this thesis has also produced new evidence on the association of blood lipids with dementia outcomes in previously unanalysed cohorts and provided additional information on a previously under-studied relationship (lipids/LRA and vascular dementia).

A further strength of this thesis is the production of software to support the novel evidence synthesis techniques used. Extensive documentation has been written to guide users through usage of the tools and example data are provided, enabling future researchers to readily apply the methods described. 

Finally, substantial effort has been invested to make the research documented in this thesis as reproducible as possible - this is documented more fully in Appendix \@ref(disc-repro-research).

&nbsp;<!----------------------------------------------------------------------->  

### Weaknesses

However, there are also four key limitations to this thesis. As with many studies of dementia outcomes, a limiting factor in the interpretation of the results is the absence of a detailed pathological mechanism. It is possible that statins have a true effect on dementia risk via some pathway other than lipid-regulation, but without knowledge of the mechanism, the plausibility of this relationship cannot be assessed. 

Secondly, each analysis presented here makes use of secondary data sources, be it published literature, electronic health records, or existing cohorts. Secondary data can limit the type of analyses performed (for example, in the IPD analysis presented in Chapter \@ref(ipd-heading), absence of time-to-event data prevented the use of hazard ratios to quantify dementia risk) and the validity of the data if collected for purposes other than research. For example, the accuracy of dementia diagnoses in electronic health records is known to be variable.[@wilkinson2018]

Thirdly, missing evidence was a common limitation across this thesis. In Chapters \@ref(sys-rev-methods-heading) & \@ref(sys-rev-results-heading), several studies stated that they did not report the results of an analysis because the results were not significant. This was particularly common among non-randomised studies of exposure examining blood lipids directly. Similarly, an absence of evidence on vascular dementia, potentially due to a publication bias mechanism, limited the analysis of this outcome. Missing evidence was also an issue in the IPD meta-analysis reported in Chapter \@ref(ipd-heading), in the form of a poor response to data access requests. In addition, the absence of empirically based distributions of bias/indirectness for use with the triangulation framework limited the credibility of the results produced.

A final weakness stems from the geographical focus of the data analysed in this thesis. All primary analysis presented drew on data from the UK (CPRD, CaPS, EPIC Norfolk, Whitehall II), while the majority of studies identified by the review were based in westernised countries (Figure \@ref(fig:cohortLocations)). This, combined with the limited evidence for different ethnicities available even within high income settings, may limit the generalisability of the results presented to different populations. 

&nbsp;<!----------------------------------------------------------------------->  

## Lessons learned

As part of a reflective learning process throughout my PhD, I maintained a catalogue of failures (available in Appendix \@ref(appendix-catalogue-failures)) describing analytical mistakes, failed experiments, and unsuccessful grant applications. However, I found there was one central learning point from this thesis, namely, to be slightly less ambitious when planning future research projects. 

The proposal for the program of research underpinning this thesis was created in advance of starting my PhD because a detailed plan was required in order to secure the funding that supported me through my studies. In hindsight, the decision to take a broad approach to the inclusion of dementia outcomes resulted in a larger workload than anticipated, particularly when also considering evidence from multiple different study designs. Additionally, as dementia subtypes likely have very different aetiological pathways, it may have been better to focus on a single subtype (e.g., Alzheimer's disease) when considering the causal effects of lipids. Similarly, attempting to undertake a full individual participant data meta-analysis as a single part of a larger program of research was overly ambitious, given that data cleaning and harmonisation for just three cohorts turned out to be a substantial undertaking. 

In the future, armed with the experience gained through conducting the research presented here, I will be better placed to scope and design research projects.

&nbsp;<!----------------------------------------------------------------------->  

## Future work

Several avenues of future research are proposed, building on the novel work presented here. These are grouped by topic in the following sections.

&nbsp;<!----------------------------------------------------------------------->  

### Generation of new evidence from RCTs

It is customary at this point in the discussion of results based (primarily) on observational data to recommend that a large-scale randomised controlled trial (RCT) be performed to assess the effect of the proposed intervention. Given the costs and logistical challenges associated with trials examining outcomes with long prodromal periods such as dementia, a more efficient approach is offered by the opportunistic post-trial follow-up of existing RCTs of lipid-regulating agents.

This approach has already been used to assess long-term (11-20 years) safety outcomes of statin use, using participant recontact[@group2011] and linkage with electronic health records to identify events.[@ford2016] A similar approach could be used to assess the impact of randomisation to statins at midlife on subsequent risk of dementia outcomes. Use of data linkage would represent the most cost-efficient approach,[@llewellyn-bennett2018] though as noted in Chapter \@ref(cprd-analysis-heading), there is the potential for non-differential misclassification when defining dementia outcomes using electronic health records.

&nbsp;<!----------------------------------------------------------------------->  

### Evidence on vascular dementia

As highlighted by the results of the systematic review presented in Chapter \@ref(sys-rev-results-heading), there is an absence of evidence on vascular dementia across the existing evidence base. While the primary studies presented here go some way towards supplementing this evidence base, future work is needed both to investigate the reasons for this evidence gap (e.g., due to an absence of primary data, challenges in the analysis of this outcome as documented in Chapter \@ref(cprd-analysis-heading), or a publication bias mechanism) and to address it. 

However, it seems unlikely that further analysis of observational data alone will be sufficient to investigate this outcome, given the evidence of strong confounding by indication presented by the analysis of statins and vascular dementia (Chapter \@ref(cprd-analysis-heading)). Even using cutting-edge methods, such as a target trial emulation approach, previous analyses have not replicated the known protective effect of statins on coronary heart disease identified by RCTs (see Section \@ref(cprd-confounding-by-ind)).[@danaei2013] Similarly, available Mendelian randomisation studies are limited to a single one-sample analysis of HMGCR variants as a proxy for statin treatment. This study suggested a protective effect of lipid-lowering on vascular dementia, although there was a moderate risk of bias in this analysis and the effect was attenuated to the null when including a wider range of lipid-lowering variants.

Taken together, these points reinforce the need for a large-scale genome-wide association study (GWAS) of vascular dementia, similar to those currently available for Alzheimer's disease, to identify genetic variants associated with this outcome that future two-sample Mendelian randomisation studies could exploit. While GWAS of this outcome are likely to be methodologically challenging, given the difficulty in diagnosing "pure" vascular dementia, it would be a worthwhile endeavour and allow for the assessment of genetically driven risk factors beyond those considered in this thesis.

&nbsp;<!----------------------------------------------------------------------->  

### Preprinted evidence

In terms of evidence synthesis methodology, future work on preprinted evidence could address how to handle discrepancies between the preprinted and published versions of a paper when identifying results for inclusion in a synthesis. This will be particularly important in cases where the results are substantially different between the two versions or if a result available in the preprint manuscript is not presented in the published version.

The `medrxivr` tool enables programmatic searching of health-related preprints, and future work could incorporate the tool, along with software to search other literature sources, into an automated searching pipeline as part of a living systematic review.[@elliott2014] In addition, the ready access to preprint data afforded by the tool will enable future meta-epidemiological studies to examine factors which may influence eventual publication (for example,  significant results, geographical location/gender/career stage of first author, or some other factor). Finally, the tool will allow future research to assess the impact of peer review and editorial guidelines on manuscripts through comparison of the same paper at two stages (preprinted versus published). This approach was used to explore the impact of editorial polices on open data sharing, as discussed in Chapter \@ref(sys-rev-tools-heading), but could be applied to other aspects of the publication process.

&nbsp;<!----------------------------------------------------------------------->  

### Reviewing Mendelian randomisation studies

As noted in Chapter \@ref(sys-rev-results-heading), methods for the inclusion of Mendelian randomisation studies in evidence synthesis exercises are not yet sufficiently developed, particularly in comparison to other study designs. Future work could aim to validate search strategies for this study design, paying particular attention to the range of terms used to define the analytical approach (e.g., genetic instrumental variable analysis). In addition, as discussed in Section \@ref(tri-accuracy), the lack of an established risk-of-bias tool for Mendelian randomisation studies limits subsequent analyses that require systematic assessment of bias, such as the quantitative triangulation framework proposed here. Creation of a domain-based tool for this study design, which accounts for the differences in potential biases between one- and two-sample approaches, should be considered a priority. 

Finally, the inclusion of multiple two-sample Mendelian randomisation studies using identical summary statistics can falsely increase the precision of the summary effect estimate if treated as independent results. It would be interesting to examine how this issue has been addressed in existing reviews of Mendelian randomisation studies, and based on this research, develop best practice guidance for future evidence syntheses.

&nbsp;<!----------------------------------------------------------------------->  

### Systematic reviews and quantitative triangulation

Quantitative triangulation is an area ripe for future work. The approach presented here will benefit from future meta-epidemiological studies to better define the impact of bias/indirectness, as discussed in detail in Section \@ref(tri-prior-def). Similarly, future work could expand the framework proposed here to account for meta-biases, such as those introduced by missing evidence. Tools such as ROB-ME will enable this, but the optimum method to adjust for this synthesis-level - as opposed to study-level - bias will need to be determined. Finally, the application of the framework to other causal questions will help to identify sticking points and may lead to refinement of the process.

<!-- TODO Could also talk here about how applying it across multiple questions would enable the development of a database of prespecified priors. -->

&nbsp;
<!----------------------------------------------------------------------------->

## Overall conclusions

To conclude, this thesis has provided new evidence concerning the role of blood lipids as a modifiable risk factor for dementia and highlighted the considerable uncertainty that still remains in relation to this causal question. In addition, it has developed new methods and tools, specifically around the inclusion of preprints in systematic reviews and the quantitative triangulation of evidence sources, which will enable future evidence synthesists to better address important causal questions.
