---
#########################################
# options for knitting a single chapter #
#########################################
output:
  bookdown::html_document2: default
  bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
documentclass: book
---

# Preface {-}

\adjustmtc 
<!-- For PDF output, we must include this LaTeX command after unnumbered headings, otherwise the numbers in the mini table of contents will be incorrect -->

```{r word-count, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)

words01 <- as.numeric(wordcountaddin::word_count("01-Chp1-Introduction.Rmd"))
words02 <- as.numeric(wordcountaddin::word_count("02-Chp2-Systematic-Review.Rmd"))
words03 <- as.numeric(wordcountaddin::word_count("03-Ch3-CPRD-Analysis.Rmd"))
words04 <- as.numeric(wordcountaddin::word_count("011-Chp2-Background.Rmd"))
words05 <- as.numeric(wordcountaddin::word_count("012-Chp-Systematic-Review-Tools.Rmd"))
words06 <- as.numeric(wordcountaddin::word_count("20-Discussion.Rmd"))
 
words <- words01 + words02 + words03 + words04 + words05 + words06

date <- format(Sys.time(),"%Y%m%d")

tmpWords <- data.frame(words = words,
                       date = date,
                       days = as.numeric(0),
                       words_per_day = as.numeric(0),
                       target = as.numeric(0), stringsAsFactors = FALSE)

masterWords <- read.csv("words/words.csv", header = TRUE)

#masterWords$date <- as.Date(as.character(masterWords$date), "%Y%m%d")



tmpWords$days <- as.numeric(as.Date(tmpWords$date[length(tmpWords$date)],"%Y%m%d")+1 - as.Date(as.character(masterWords$date[1]),"%Y%m%d"))

tmpWords$words_per_day <- as.numeric(masterWords[length(masterWords$words),2])/tmpWords$days

tmpWords$target <- tmpWords[length(tmpWords$days),3]*200

masterWords <- rbind(masterWords,tmpWords)

masterWords <- masterWords %>%
  group_by(date) %>%
  filter(words == max(words))

write.csv(file = "words/words.csv", x = masterWords, col.names = FALSE, row.names = FALSE)



change <- masterWords$words[length(masterWords$words)] - masterWords$words[length(masterWords$words)-1]

```

* Word count: `r masterWords$words[length(masterWords$words)]` words

* Change since last day: `r change` words

* Days: `r masterWords$days[length(masterWords$days)]` days

* Words per day: `r masterWords$words_per_day[length(masterWords$words_per_day)]`

```{r, echo = FALSE, warnings = FALSE, message=FALSE}
library(ggplot2)

masterWords <- read.csv("words/words.csv", header = TRUE)

masterWords$date <- as.numeric(masterWords$date)

ggplot(data = masterWords, aes(x=date))+
  geom_point(aes(y=words)) +
  geom_line(aes(y=words)) +
  geom_point(aes(y=target), colour = "red") +
  geom_line(aes(y=target), colour = "red")

```