---
#####################
## thesis metadata ##
#####################
title: |
   Lipids and dementia:\
   An investigation of their relationship
   
author: Luke A McGuinness
college: 
degree: Doctor of Philosophy in Population Health Sciences
degreedate: TBC
abstract: |
  `r paste(readLines("front-and-back-matter/_abstract.Rmd"), collapse = '\n  ')`
acknowledgements: |
  `r paste(readLines("front-and-back-matter/_acknowledgements.md"), collapse = '\n  ')`
declaration: |
  `r paste(readLines("front-and-back-matter/_declaration.Rmd"), collapse = '\n  ')`
dedication: For Brendan McHugh
covidStatment: |
  `r paste(readLines("front-and-back-matter/_covidStatment.Rmd"), collapse = '\n  ')`
abbreviations: "front-and-back-matter/abbreviations" # path to .tex file with abbreviations

#######################
## bibliography path ##
#######################
bibliography: 
    - "bibliography/references.bib"
csl: bibliography/nature.csl
bibliography-heading-in-pdf: Bibliography

#####################
## PDF formatting  ##
#####################
abstractseparate: true  # include front page w/ abstract for examination schools?
bib-humanities: false   #set to true if you want in-text references formatted as author-year
doi-in-bibliography: true #set to true if you want DOI's to be shown in the bibliography
draft: false # add as DRAFT mark in the footer?
page-layout: twoside #'nobind' for PDF output (equal margins), 'twoside' for two-sided binding (mirror margins and blank pages), leave blank for one-sided binding (left margin > right margin)
hidelinks: true #if false, the PDF output highlights clickable links with a colored border - you will probably want to set this to true for PDF version you wish to physically print
toc-depth: 2 # depth of heading to include in table of contents
lof: true # list of figures in front matter?
lot: true # list of tables in front matter?
mini-toc: true  # mini-table of contents at start of each chapter? (this just prepares it; you must also add \minitoc after the chapter titles)
mini-toc-depth: 1
mini-lot: false  # mini-list of tables by start of each chapter?
mini-lof: false  # mini-list of figures by start of each chapter?

params:
  corrections: true # set false to stop applying blue background to blocks of corrections

#####################
## output options  ##
#####################
output:
  bookdown::pdf_book:
    template: templates/template.tex
    keep_tex: true
    citation_package: default 
    pandoc_args: ["--lua-filter=scripts_and_filters/correction_filter.lua", "--csl","bibliography/nature.csl"] #remove filter to stop applying blue background to inline corrections
  bookdown::gitbook:
    css: templates/style.css
    download: ["pdf"]
    output_dir: "docs"
    split_bib: false
    config:
      toc:
        before: |
          <li><a href="./">Thesis - Draft</a></li>
        after: |
          <li><a href="https://github.com/mcguinlu/thesis" target="blank">Associated repository</a></li>
      sharing:
        facebook: false
        twitter: yes
        all: false
  bookdown::word_document2:
    output_dir: "docs"
    toc: true
    toc_depth: 2
    reference_docx: templates/word-styles-reference-01.docx
    number_sections: false   
link-citations: true
documentclass: book

---

```{r create_chunk_options, include=FALSE, eval=knitr::is_latex_output()}
source('scripts_and_filters/create_chunk_options.R')
source("R/helper.R")
options(scipen=999)
```

<!--
Include the create_chunk_options chunk above at the top of your index.Rmd file
This will include code to create additional chunk options (e.g. for adding author references to savequotes)
If you need to create your own additional chunk options, edit the file R/create_chunk_options.R
-->

```{r introduction, child = 'front-and-back-matter/_00-introduction.Rmd'}
```
