# Covering material {-}

\adjustmtc 
<!-- For PDF output, we must include this LaTeX command after unnumbered headings, otherwise the numbers in the mini table of contents will be incorrect -->

```{r word-count, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)

options(scipen=999)

get_words_short <- function(){

files <- list.files(path = here::here(), pattern = "\\.Rmd$")

files <- files[which(!(files %in% c("_main.Rmd","index.Rmd")))]

words_v <- c()

for (file in 1:length(files)) {
  tmp <- wordcountaddin::word_count(here::here(files[file]))
  words_v <- c(words_v, tmp)
}

words <- sum(words_v)

return(words)

}

get_words <- function(){

files <- list.files(path = here::here(), pattern = "\\.Rmd$")

files <- files[which(!(files %in% c("_main.Rmd","index.Rmd", "tmp.Rmd")))]

words_v <- c()

for (file in 1:length(files)) {
  tmp <- wordcountaddin::word_count(here::here(files[file]))
  words_v <- c(words_v, tmp)
}


# TODO Work out what an appropriate number of words for tables is
# Sum words and add number of words in tables
words <- sum(words_v) + 250

date <- as.character(format(Sys.time(),"%Y%m%d"))
time <- as.character(format(Sys.time(),"%H%M"))

tmpWords <- data.frame(words = words,
                       date = date,
                       time = time)

masterWords <- read.csv(here::here("data","words","words.csv"),
                        header = TRUE)

masterWords <- rbind(masterWords,
                     tmpWords) %>%
  dplyr::group_by(date) %>%
  slice(which.max(time)) %>%
  dplyr::ungroup()

return(masterWords)

}

words <- get_words()

write.csv(file = here::here("data","words","words.csv"),
          x = words,
          col.names = FALSE,
          row.names = FALSE)



start_date <- as.Date("20201124", format="%Y%m%d")

max_date <- as.Date(max(words$date), format="%Y%m%d")

words_today <- words$words[which(as.Date(words$date, format="%Y%m%d")==max_date)]

date_diff <- as.numeric((max_date) - start_date)

target <- (date_diff*97) + 5580

words_behind <- words$words[which(words$date == max(words$date))] - target

words_new_today <- words$words[which(words$date == max(words$date))] - words$words[length(words$words)-1]

target_df <- data.frame(date = c(start_date,as.Date("20211116", format="%Y%m%d")),
                           words = c(5580, 40000))

words$date <- as.Date(words$date, format="%Y%m%d")

```

Word count: `r words_today`

Days: `r date_diff`

Words behind: `r format(words_behind, scientific = F)`

Words today: `r words_new_today`

&nbsp;  

&nbsp;  

```{r word-count-fig, echo=FALSE, warning=FALSE, message=FALSE}
ggplot(mapping = aes(x=date,y=words)) +
  geom_line(data = target_df, colour = "black", linetype = 2) +
  geom_hline(yintercept = 40000, colour = "black", linetype = 2) +
  geom_vline(xintercept = as.numeric(as.Date("20211116", format="%Y%m%d")), colour = "black", linetype = 2) +
  geom_vline(xintercept = as.numeric(as.Date("20211216", format="%Y%m%d")), colour = "red") +
  scale_x_date(limits = c(as.Date("20201124", format="%Y%m%d"),as.Date("20211231", format="%Y%m%d"))) +
  geom_step(data = words, colour = "red")

```

